In [10]:
import numpy
import scipy.special

In [18]:
# neural net class
class NeuralNetwork(object):
    def __init__(self, input_nodes, hidden_nodes, output_notes, learning_rate=0.4):
        # Node Dimensions 
        self.input_nodes = input_nodes
        self.hidden_nodes = hidden_nodes
        self.output_notes = output_notes
        
        # Learning Rate
        self.lr = learning_rate
        
        # Activation Function (Signmoid)
        self.activation_function = lambda x: scipy.special.expit(x)
        
        #Weights
        self.w_input_hidden = self.gen_weights(
            self.input_nodes, self.hidden_nodes
        )
        
        self.w_hidden_output = self.gen_weights(
            self.hidden_nodes, self.output_notes
        )
        
    def train(self, inputs_list, targets_list):
        inputs = numpy.array(inputs_list, ndmin=2).T
        targets = numpy.array(targets_list, ndmin=2).T
        
        hidden_inputs = numpy.dot(self.w_input_hidden, inputs)
        hidden_outputs = self.activation_function(hidden_inputs)
        
        final_inputs = numpy.dot(self.w_hidden_output, hidden_outputs)
        final_outputs = self.activation_function(final_inputs)
        
        output_errors = targets - final_outputs
        hidden_errors = numpy.dot(self.w_hidden_output.T, output_errors)
        
        self.w_hidden_output += self.weight_delta(output_errors, hidden_outputs, final_outputs)
        self.w_input_hidden += self.weight_delta(hidden_errors, hidden_outputs, final_outputs)
    
    def query(self, inputs_list):
        inputs = numpy.array(inputs_list, ndmin=2).T
        
        hidden_inputs = numpy.dot(self.w_input_hidden, inputs)
        
        hidden_outputs = self.activation_function(hidden_inputs)
        
        final_inputs = numpy.dot(self.w_hidden_output, hidden_outputs)
        
        final_outputs = self.activation_function(final_inputs)
        
        return final_outputs
    
    @staticmethod
    def gen_weights(nodes1, nodes2):
        return numpy.random.normal(
            0.0,
            pow(nodes2, -0.5),
            (nodes2, nodes1)
        )
    
    def weight_delta(self, errors, output1, output2):
        return self.lr * numpy.dot(
            (errors * output2 * (1.0 - output2)),
            numpy.transpose(output1)
        )

In [19]:
# Initialize size of nework with  
inode = 3
hnode = 3
onode = 3

n = NeuralNetwork(inode, hnode, onode)

In [13]:
# The initial weights of an untouched NN
weight_set1 = n.w_input_hidden
print(weight_set1)

[[ 0.31158013 -0.98730772  0.06083078]
 [-0.34807992 -0.52448014 -0.7949376 ]
 [-0.27373261  0.57817339 -0.09384964]]


In [14]:
# The results of a query with 3 inputs
entry = [1.0, 0.5, -1.5]
result = n.query(entry)
print(result)

[[ 0.59601309]
 [ 0.51838343]
 [ 0.52236893]]


In [15]:
# The initial weights of an untouched NN
weight_set1 = n.w_input_hidden
print(weight_set1)

[[ 0.31158013 -0.98730772  0.06083078]
 [-0.34807992 -0.52448014 -0.7949376 ]
 [-0.27373261  0.57817339 -0.09384964]]


In [16]:
# Convert result into input array to use as the target
# With the same inputs, and setting the target to the same as the result,
#     we should see no change in the network.
target = list(result.T[0])
n.train(entry, target)
print(n.w_input_hidden)

[[ 0.31158013 -0.98730772  0.06083078]
 [-0.34807992 -0.52448014 -0.7949376 ]
 [-0.27373261  0.57817339 -0.09384964]]


In [17]:
# Now with a change to the target, we should see a change in weights.
target[0] += 1
n.train(entry, target)
print(n.w_input_hidden)

[[ 0.34456739 -0.93833002  0.10197612]
 [-0.33077823 -0.49879152 -0.77335702]
 [-0.29838239  0.54157472 -0.12459556]]
